######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 30 19:16:44 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += createDialog.h mainwindow.h read.h
SOURCES += createDialog.cpp main.cpp mainwindow.cpp read.cpp
RESOURCES += window.qrc
